`timescale 1ns / 1ps

//////////////////////////////////////////////////////////////////////////////////
// Module Name : UART_transmitter
// Project     : UART Transmitter and Receiver (Verilog HDL)
// Description :
//   Implements an 8-bit UART transmitter using a finite state machine (FSM).
//   The transmitter converts parallel input data into a serial UART frame
//   consisting of:
//
//     - 1 Start Bit  (Logic 0)
//     - 8 Data Bits  (LSB First)
//     - 1 Stop Bit   (Logic 1)
//
//   Transmission timing is controlled by an external baud_tick signal
//   generated by the baud rate generator module.
//
// Features:
//   - Parameterized FSM-based design
//   - LSB-first serialization
//   - One baud period per transmitted bit
//   - tx_start controlled frame transmission
//   - tx_done indication upon frame completion
//
// Dependencies:
//   - baud_rate_generator.v
//
// Author      : M.V.S.Charith
//////////////////////////////////////////////////////////////////////////////////

module UART_transmitter(
    input clk,
    input reset,
    input baud_tick,
    input tx_start,
    input [7:0] tx_data,
    output tx_serial_out,
    output tx_done
    );
   
    parameter IDLE = 0, START = 1, DATA_BITS = 2, STOP = 3, DONE = 4;
    reg [2:0] state, next_state; 
    reg [2:0] count;
    
    reg out_reg;
    
    always @(*) begin
        case(state)
            IDLE: begin next_state = tx_start? START: IDLE; out_reg = 1'b1; end
            START: begin next_state = DATA_BITS; out_reg = 1'b0; end
            DATA_BITS: begin next_state = (count==3'd7)? STOP: DATA_BITS; out_reg = tx_data[count]; end
            STOP: begin next_state = DONE; out_reg = 1'b1; end
            DONE: begin next_state = IDLE; out_reg = 1'b1; end
            default: begin next_state = IDLE; out_reg = 1'b1; end
        endcase
    end    
    
    always @(posedge clk) begin
        if(reset) begin
            state <= IDLE;
            count <= 3'b0;
        end else if(next_state!=DONE) begin 
            if(baud_tick) begin
                state <= next_state;
                if(next_state==DATA_BITS && state!=DATA_BITS)
                    count <= 3'b0;
                else if(state==DATA_BITS)
                    count <= count+1;
                else
                    count <= 3'b0;
            end
       end else
            state <= next_state;
    end
    
    assign tx_serial_out = out_reg;
    assign tx_done = (state==DONE);
endmodule
